### ISSUE TITLE
実績レポート/有支レポートの入力区分を一関の主要得意先に変更

### ISSUE THREAD

**Issue by jms-funato** [jms-web/TK#5]
経理システムと同様に、本社の入力区分(豊鉄、タチエス、FTS)を
一関の主要得意先の入力区分(TTC、KIK、その他)に変更
ただし、ベースレポートは全て「その他」区分のものを使用

- [x] 実装
- [ ] 一関動作確認
- [ ] 本社へ完了報告 Win7 Office入替確認

**Comment by jms-fukuta** [comment]
杉屋さんに手配済です
